### ISSUE TITLE
Feeback, Bugs, Nits and Improvement proposals for the Dashboard rewrite

### ISSUE THREAD

**Issue by soad003** [graphsense/graphsense-dashboard#296]
**Bugs or Functions Missing:**

- [x] Pressing enter when search-bar is in focus (text 0x06012c8cf97bead5deae237070f9587f8e7a266d) does not add node.
- [x] Transactions are not loaded in property box for ethereum addresses (eg. 0x06012c8cf97bead5deae237070f9587f8e7a266d), bitcoin works fine. 
- [x] # of address tags is not shown correctly in property box (eg. binance.com, 34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo, has 5 tags but 0 is shown)
- [x] Clicking on the edges in the graph does not open tx view.

**UI Nits:**

- [x] ~~Missing translation for Akte (English selected). ~~ (moved to #300)
- [x] OK button overlaps textbox on API key popup (firefox and chromium)
- [x] Search bar is to small for eth address (line break). Probably duplicate of this (https://github.com/graphsense/graphsense-dashboard/issues/293)
- [x] Search bar button is a pixel or two smaller than the bar. Looks misaligned
- [x] Search bar becomes smaller on focus. 
- [x] ~~Can not change language since popup disappears when drop down is selected.~~ (moved to #309)
- [x] Nodes (Entities) can be expanded and collapsed. For me only expanding works.
- [x] Zooming steps (in the graph view) are a bit big. 
- [x] ~~Moving addresses to boundaries makes them shake and sometimes jump to weird locations~~ (moved to #310)
- [x] Horizontal scrollbar on search entity tool
- [x] ~~Searching that results in a large results set opens log with an error (and a lot of other content). Instead of a user comprehensible error message~~ (moved to #308)
- [x] There is no button to open or close the log. (although clicking the footer works)
- [x] There is no, no entries available view, for the lists in the property box.
- [x] Labels in such list and their sorting button should be separated by at least some white-space
- [x] Address property box shows the entity tag and ID without space. Might be duplicate of this (https://github.com/graphsense/graphsense-dashboard/issues/295)
- [x] The fields in the aktenzeichen view overlap each other (firefox and chromium)
- [x] Labels of the Legend are not clickable anymore

**Improvement Proposals:**

- [x] ~~I think it would be nice if the legend is visible all the time. (Maybe in the footer instead of top right)~~ (moved to #311)

**Detailed Feedback and Screenshots:**
A longer descriptions of the issues including feedback can be found in this file:
[feedback_170622.pdf](https://github.com/graphsense/graphsense-dashboard/files/8927487/feedback_170622.pdf)
